### ISSUE TITLE
Error in CCCC plugin: cccc.xml not found

### ISSUE THREAD

**Issue by git-afsantos** [git-afsantos/haros_plugins#14]
```
ERROR:haros.analysis_manager:Plugin haros_plugin_cccc ran into an error.
DEBUG:haros.analysis_manager:Traceback (most recent call last):
  File "/home/<user>/haros/analysis_manager.py", line 480, in _analysis
    plugin.analysis.analyse_package(iface, scope)
  File "/home/<user>/haros/plugin_manager.py", line 76, in analyse_package
    self.module.package_analysis(iface, scope)
  File "/home/<user>/.local/lib/python2.7/site-packages/haros_plugin_cccc/plugin.py", line 68, in package_analysis
    with open(os.path.join(outdir, "cccc.xml"), "r") as handle:
IOError: [Errno 2] No such file or directory: '/tmp/tmp0NDzeR/haros_plugin_cccc/<some_package_analyzed>/cccc.xml'
```

This is past the point of calling `cccc` with subprocess. It is not creating the file for whatever reason.
Perhaps a different version? Perhaps a package without C++ code?

**Comment by git-afsantos** [comment]
This was reported for CCCC Version 3.1.4.

**Comment by git-afsantos** [comment]
The package did not have any C++ files. Perhaps add a condition to `package_analysis` to skip packages without C++.
