### ISSUE TITLE
AssertionError in Pylint plugin

### ISSUE THREAD

**Issue by git-afsantos** [git-afsantos/haros_plugins#15]
```
ERROR:haros.analysis_manager:Plugin haros_plugin_pylint ran into an error.
DEBUG:haros.analysis_manager:Traceback (most recent call last):
  File "/home/<user>/haros/analysis_manager.py", line 475, in _analysis
    plugin.analysis.analyse_file(iface, scope)
  File "/home/<user>/haros/plugin_manager.py", line 70, in analyse_file
    self.module.file_analysis(iface, scope)
  File "/home/<user>/.local/lib/python2.7/site-packages/haros_plugin_pylint/plugin.py", line 46, in file_analysis
    report_issue(iface, line, fun, cls, msg)
  File "/home/<user>/.local/lib/python2.7/site-packages/haros_plugin_pylint/plugin.py", line 60, in report_issue
    assert msg_type == "F"
AssertionError
```

It seems that there is either a new message type (not likely) or messages are being reported in another format. Check newer versions of Pylint for changes.

**Comment by git-afsantos** [comment]
This was reported for Pylint Version 1.9.5.
